- name: dnsmasqのインストール
  apt:
    name: dnsmasq
    state: latest
    update_cache: true
    cache_valid_time: 3600
- name: dnsmasq.conf copy
  template: src=templates/dnsmasq.conf dest=/etc/dnsmasq.conf #mode=0644
- name: systemd-resolved 自動起動停止
  service:
    name: systemd-resolved
    enabled: no
    state: stopped
- name: dnsmasq自動起動登録
  service:
    name: dnsmasq
    enabled: yes
    state: started