# update upgrade
- hosts: all
  become: true
  roles:
    - role: aptupdate
# dnsサーバ構築
- hosts: build
  become: true
  roles:
    - role: dnsmasq
# cri-oのインストール
- hosts: all
  become: true
  vars:
    os: xUbuntu_20.04
    version: "1.20"
  roles:
    - role: cri-o_file
# kubeコマンドのインストール
- hosts: kuberenetes
  become: true
  roles:
    - role: k8s-cri-o
# マスターの構築
- hosts: master
  vars:
    cri_url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml #flannel
    # cri_url: https://docs.projectcalico.org/manifests/calico.yaml #calico
  roles:
    - role: kubeadm_init
    - role: kubeadm_get
# workerの構築
- hosts: worker
  roles:
    - role: kubeadm_add
#kuberentesのadmin.confの情報を取得する
- hosts: master
  become: true
  roles:
    - role: get_kubectl_adminconf
#podman kubectlコマンドが実行できるようにする。
- hosts: build
  roles:
    # - role: docker_file
    - role: podman
    - role: add_kubectl
    - role: add_kubectl_adminconf
# #operaterを構築する
# - hosts: localhost
#   become: true
#   roles:
#     - role: operater_sdk_install
